language: csharp
mono: none
solution: KalturaClient.sln
dotnet: 2.1.801
mono:
  - latest
  - 3.12.0
  - 3.10.0
script:
  - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" -e "s#@SERVICE_URL@#https://www.kaltura.com#g" -i KalturaClientTester/ClientTester.cs
  - dotnet build ./KalturaClientTester/KalturaClientTester.csproj -c Release -f netcoreapp2.0
  - dotnet build ./KalturaClientTester/KalturaClientTester.csproj -c Release -f net45 -v n
  - cd KalturaClientTester/bin/Release/net45 && mono KalturaClientTester.exe
  - cd ../netcoreapp2.0 && dotnet KalturaClientTester.dll
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Noad.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always
