language: csharp
mono: none
solution: KalturaClient.sln
dotnet: 2.1.801
mono:
  - latest
  - 3.12.0
  - 3.10.0
script:
 - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" -e "s#@SERVICE_URL@#https://www.kaltura.com#g" -i KalturaClientTester/ClientTester.cs
 - "msbuild -t:restore,build"




# language: csharp
# mono:
#   - latest
#   - 3.12.0
#   - 3.10.0
# install:
#   - sudo apt-get install -y gtk-sharp2
#   - nuget restore KalturaClient.sln
# script: 
#     - xbuild KalturaClient.sln && cd ./KalturaClientTester/bin/Debug/ &&  echo | mono KalturaClientTester.exe
# notifications:
#  email:
#     recipients:
#       - moshe.maor@kaltura.com
#       - jess.portnoy@kaltura.com
#       - Noad.arad@kaltura.com
#       - Elad.cohen@kaltura.com
#       - Jonathan.Kanarek@kaltura.com
#     on_success: change
#     on_failure: always
